package mcp

import (
	"encoding/json"
	"fmt"
	"github.com/sannysanoff/mcphost/pkg/history"
	"github.com/sannysanoff/mcphost/pkg/system"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/charmbracelet/log"
	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
	// Import the system package. After `go generate` runs, this package will contain
	// the 'Symbols' variable generated by yaegi-extract.
	systemsymbols "github.com/sannysanoff/mcphost"
)

// Agent represents a loaded agent with its interpreter and methods
type Agent interface {
	// GetSystemPrompt returns the agent's default system prompt
	GetSystemPrompt() string

	// NormalizeHistory processes and normalizes message history
	NormalizeHistory(messages []history.HistoryMessage) []history.HistoryMessage

	// Filename returns the source file name of this agent
	Filename() string

	GetTaskForModelSelection() string
}

type yaegiAgent struct {
	filename       string
	fullPath       string
	interpreter    *interp.Interpreter
	lastCheck      int64
	lastModTime    time.Time
	implementation *system.AgentImplementationBase
}

func makePascalCase(name string) string {
	parts := strings.Split(name, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// ensureImplementationReady checks if the agent script has been modified, reloads it if necessary,
// and ensures that a.implementation is populated by calling 'agents.GetImplementation()' from the script.
func (a *yaegiAgent) ensureImplementationReady() error {
	now := time.Now().Unix()
	needsLoadImplementation := a.implementation == nil // Load if never loaded

	// Check for file modification at most once per second.
	// The lastCheck field is updated regardless of whether a file stat occurs.
	if now-a.lastCheck >= 1 {
		a.lastCheck = now
		info, err := os.Stat(a.fullPath)
		if err != nil {
			// If stat fails, we can't determine if reload is needed, so error out.
			// This also prevents hammering Stat on a missing file.
			a.implementation = nil // Invalidate current implementation if file is inaccessible
			return fmt.Errorf("failed to stat agent file %s: %w", a.fullPath, err)
		}

		if info.ModTime().After(a.lastModTime) {
			log.Info("Agent file changed, reloading.", "agent", a.filename, "path", a.fullPath)
			content, err := os.ReadFile(a.fullPath)
			if err != nil {
				a.implementation = nil // Invalidate on read error
				return fmt.Errorf("failed to read agent file %s: %w", a.fullPath, err)
			}

			// Re-evaluate the script. This might redefine symbols in the interpreter.
			_, err = a.interpreter.Eval(string(content))
			if err != nil {
				a.implementation = nil // Invalidate on eval error
				return fmt.Errorf("failed to re-evaluate agent code for %s: %w", a.filename, err)
			}
			a.lastModTime = info.ModTime()
			needsLoadImplementation = true // Force reload of implementation after script re-evaluation
			log.Debug("Agent script re-evaluated successfully.", "agent", a.filename)
		}
	}

	if needsLoadImplementation {
		log.Debug("Attempting to load/reload agent implementation from script.", "agent", a.filename)
		// Attempt to get the agent implementation from the script.
		// Assumes agent scripts define "agents.GetImplementation() (*system.AgentImplementationBase)".
		baseName := strings.Title(strings.TrimSuffix(filepath.Base(a.filename), ".go"))
		val, err := a.interpreter.Eval(makePascalCase(baseName) + "New()")
		if err != nil {
			a.implementation = nil // Ensure implementation is nil if fetching fails
			return fmt.Errorf("failed to call GetImplementation in agent script %s: %w. Ensure GetImplementation exists and returns *system.AgentImplementationBase.", a.filename, err)
		}

		impl, ok := val.Interface().(*system.AgentImplementationBase)
		if !ok {
			a.implementation = nil
			return fmt.Errorf("GetImplementation in agent script %s did not return *system.AgentImplementationBase, got %T", a.filename, val.Interface())
		}
		if impl == nil {
			a.implementation = nil
			return fmt.Errorf("GetImplementation in agent script %s returned nil", a.filename)
		}
		a.implementation = impl
		log.Info("Agent implementation loaded/reloaded successfully.", "agent", a.filename)
	} else if a.implementation == nil {
		// This case should ideally not be reached if logic is correct,
		// but as a safeguard: if not needing load, but impl is nil, something is wrong.
		return fmt.Errorf("internal error: agent implementation is nil for %s without needing load", a.filename)
	}
	return nil
}

// GetSystemPrompt retrieves the system prompt from the agent's implementation.
func (a *yaegiAgent) GetSystemPrompt() string {
	if err := a.ensureImplementationReady(); err != nil {
		log.Error("Failed to get agent system prompt due to implementation error", "agent", a.filename, "error", err)
		return "" // Default value on error
	}
	// Assumes system.AgentImplementationBase.GetSystemPrompt() handles nil receiver gracefully or GetImplementation never returns nil on success.
	return a.implementation.GetSystemPrompt()
}

// GetTaskForModelSelection retrieves the task for model selection from the agent's implementation.
func (a *yaegiAgent) GetTaskForModelSelection() string {
	if err := a.ensureImplementationReady(); err != nil {
		log.Error("Failed to get agent task for model selection due to implementation error", "agent", a.filename, "error", err)
		return "default" // Default value on error
	}
	return a.implementation.GetTaskForModelSelection()
}

// NormalizeHistory delegates to the agent's implementation.
func (a *yaegiAgent) NormalizeHistory(messages []history.HistoryMessage) []history.HistoryMessage {
	if err := a.ensureImplementationReady(); err != nil {
		log.Error("Failed to normalize history due to agent implementation error", "agent", a.filename, "error", err)
		return messages // Return original messages on error
	}
	// Assumes system.AgentImplementationBase.NormalizeHistory() handles nil receiver or nil NormalizeHistoryFunc gracefully.
	return a.implementation.NormalizeHistory(messages)
}

func (a *yaegiAgent) Filename() string {
	return a.filename
}

const agentsDir = "./agents" // Assuming agents are in a directory named 'agents' relative to the running binary.

// loadAgentFromFile reads an agent file and returns an initialized Agent instance
func loadAgentFromFile(agentFilePath string) (Agent, error) {
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)
	i.Use(systemsymbols.Symbols)

	agentFileContent, err := os.ReadFile(agentFilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read agent file %s: %w", agentFilePath, err)
	}

	// Get file info for mod time
	info, err := os.Stat(agentFilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to stat agent file %s: %w", agentFilePath, err)
	}

	// Evaluate the agent's Go code
	_, err = i.Eval(string(agentFileContent))
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate agent code for %s: %w", agentFilePath, err)
	}

	// Get the implementation from the script
	val, err := i.Eval("agents.GetImplementation()")
	if err != nil {
		return nil, fmt.Errorf("failed to call GetImplementation in agent script %s after initial load: %w. Ensure GetImplementation exists and returns *system.AgentImplementationBase.", agentFilePath, err)
	}

	impl, ok := val.Interface().(*system.AgentImplementationBase)
	if !ok {
		return nil, fmt.Errorf("GetImplementation in agent script %s did not return *system.AgentImplementationBase on initial load, got %T", agentFilePath, val.Interface())
	}
	if impl == nil {
		return nil, fmt.Errorf("GetImplementation in agent script %s returned nil on initial load", agentFilePath)
	}

	log.Info("Agent script evaluated and implementation loaded successfully", "file", agentFilePath)

	return &yaegiAgent{
		filename:       filepath.Base(agentFilePath),
		fullPath:       agentFilePath,
		interpreter:    i,
		lastCheck:      time.Now().Unix(), // Initialize lastCheck to current time
		lastModTime:    info.ModTime(),
		implementation: impl,
	}, nil
}

// HandleListAgents discovers agents in the 'agents' directory and returns their default prompts.
func HandleListAgents(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "Only GET method is allowed", http.StatusMethodNotAllowed)
		return
	}

	files, err := os.ReadDir(agentsDir)
	if err != nil {
		log.Error("Failed to read agents directory", "path", agentsDir, "error", err)
		http.Error(w, "Failed to read agents directory: "+err.Error(), http.StatusInternalServerError)
		return
	}

	var agents []Agent
	for _, file := range files {
		if file.IsDir() || !strings.HasSuffix(file.Name(), ".go") || file.Name() == "agents.go" {
			continue
		}

		agentFilePath := filepath.Join(agentsDir, file.Name())
		agent, err := loadAgentFromFile(agentFilePath)
		if err != nil {
			log.Warn("Failed to load agent", "file", agentFilePath, "error", err)
			continue
		}
		agents = append(agents, agent)
	}

	type agentInfo struct {
		Name          string `json:"name"`
		DefaultPrompt string `json:"default_prompt"`
	}

	var response []agentInfo
	for _, agent := range agents {
		response = append(response, agentInfo{
			Name:          strings.TrimSuffix(agent.Filename(), ".go"),
			DefaultPrompt: agent.GetSystemPrompt(),
		})
	}

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(response); err != nil {
		log.Error("/agents: Failed to encode agents information to JSON", "error", err)
		http.Error(w, "Failed to encode response: "+err.Error(), http.StatusInternalServerError)
	}
}

// GetDefaultAgent loads and returns the default agent implementation
func GetDefaultAgent() (Agent, error) {
	return LoadAgentByName("default")
}

// LoadAgentByName loads a specific agent by its base name (e.g., "default", "research_agent")
func LoadAgentByName(agentName string) (Agent, error) {
	if agentName == "" {
		return nil, fmt.Errorf("agent name cannot be empty")
	}
	agentFileName := agentName + ".go"
	agentFilePath := filepath.Join(agentsDir, agentFileName)

	if _, err := os.Stat(agentFilePath); os.IsNotExist(err) {
		// Attempt to create a default agent file if "default" is requested and doesn't exist.
		if agentName == "default" {
			log.Info("Default agent file not found, creating one.", "path", agentFilePath)
			defaultContent := `package agents

import "github.com/sannysanoff/mcphost/pkg/system"
import "github.com/sannysanoff/mcphost/pkg/history"

// GetImplementation provides the agent's core logic and configuration.
// This function is called by MCPHost to obtain the agent's behavior.
func GetImplementation() *system.AgentImplementationBase {
	return &system.AgentImplementationBase{
		SystemPrompt: "You are a helpful assistant.",
		TaskForModel: "general_assistance",
		// NormalizeHistoryFunc is optional. If nil, messages are used as is.
		// You can define custom normalization logic here if needed.
		NormalizeHistoryFunc: func(messages []history.HistoryMessage) []history.HistoryMessage {
			// Default behavior: return messages as is.
			// Add custom normalization logic if required for this agent.
			// For example, pruning, reformatting, or adding specific context.
			return messages
		},
	}
}
`
			if errWrite := os.WriteFile(agentFilePath, []byte(defaultContent), 0644); errWrite != nil {
				return nil, fmt.Errorf("failed to create default agent file '%s': %w", agentFilePath, errWrite)
			}
			log.Info("Successfully created default agent file.", "path", agentFilePath)
			// Fall through to load the newly created file.
		} else {
			return nil, fmt.Errorf("agent file '%s' not found in '%s': %w", agentFileName, agentsDir, err)
		}
	} else if err != nil {
		return nil, fmt.Errorf("error checking agent file '%s': %w", agentFilePath, err)
	}

	return loadAgentFromFile(agentFilePath)
}
